### ISSUE TITLE
Initialize Channel without ID

### ISSUE THREAD

**Issue by pietsteph** [GetStream/stream-chat-php#55]
As stated in the documentation, the id of the channel is optional (https://getstream.io/chat/docs/php/creating_channels_backend/?language=php). But I got an error when trying to initialize channel without an id.

`Channel does not (yet) have an id`

`$channel = $client->Channel("messaging");`
`$channel->addMembers([$sender, $to]);`
`$channel->sendMessage(["text" => "Test chat from API"], $sender);`

gz#13067

**Comment by SeniYG** [comment]
Hi,

Thanks for reaching out.
The channel ID is optional if creating a channel for a list of members : https://getstream.io/chat/docs/php/creating_channels_backend/?language=php#2.-creating-a-channel-for-a-list-of-members. You need to pass those members when instantiating the channel.
Otherwise, the channel ID is required.

Hopefully this should solve your issue here. Let us know if you have more questions.

Best,

**Comment by pietsteph** [comment]
`$conversation = $client->Channel('messaging', 'thierry-jenny', ['members'=>['thierry', 'jenny']]); `
isn't the 'thierry-jenny' is the id?

**Comment by SeniYG** [comment]
Hi,

Indeed, you're right 'thierry_jenny' is actually the channel ID in the example. You can find an example of channel creation without referencing the ID in the following integration tests file : https://github.com/GetStream/stream-chat-php/blob/28d5deab77ac254c9bd66b1a02673efb6424a08a/tests/integration/IntegrationTest.php#L445

Please, let me know if you are able to make it work.

Best,

**Comment by pietsteph** [comment]
Woah, it works! Basically I've tried fill the id with null but I missed the `$channel->create($sender)` line.
I really appreciate your response and help. Thank you so much.
